apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 85.2.0
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/deploy/monitoring/helm/kube-prometheus-stack-values.yaml
    - repoURL: https://github.com/KUSITMS-CHECKMATE/MATE-SERVER.git
      targetRevision: feat/ci
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: ""
      kind: Service
      name: monitoring-kube-prometheus-coredns
      namespace: kube-system
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
    - group: apps
      kind: Deployment
      name: monitoring-kube-prometheus-operator
      namespace: monitoring
      managedFieldsManagers:
        - kube-controller-manager
    - group: monitoring.coreos.com
      kind: PrometheusRule
      namespace: monitoring
      jsonPointers:
        - /metadata/annotations
    - group: ""
      kind: Secret
      name: monitoring-grafana
      namespace: monitoring
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
