apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KUSITMS-CHECKMATE/MATE-SERVER.git
    targetRevision: feat/ci
    path: deploy/apps/mate
  destination:
    server: https://kubernetes.default.svc
    namespace: mate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
