fluent-bit:
  enabled: false
grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: true
loki:
  enabled: true
  isDefault: false
  image:
    tag: 2.9.3
  persistence:
    enabled: true
    storageClassName: local-path
    size: 10Gi
prometheus:
  enabled: false
promtail:
  enabled: false
