spring:
  application:
    name: MATE
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

deploy:
  env: ${DEPLOY_ENV:local}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL:}
