spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  ssl:
    bundle:
      pem:
        toss:
          keystore:
            certificate: ${TOSS_MTLS_CERT_PATH:false}
            private-key: ${TOSS_MTLS_KEY_PATH:false}

deploy:
  env: ${DEPLOY_ENV:prod}

toss:
  api:
    enabled: ${TOSS_API_ENABLED:true}
    ssl:
      enabled: ${TOSS_API_SSL_ENABLED:true}
      bundle: toss
  callback:
    basic-auth-header: ${TOSS_CALLBACK_BASIC_AUTH_HEADER:}
  crypto:
    decryption-key: ${TOSS_CRYPTO_DECRYPTION_KEY:}
    aad: ${TOSS_CRYPTO_AAD:}
  token:
    refresh-cache-ttl: ${TOSS_REFRESH_CACHE_TTL:1209600000}

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL:}

azure:
  storage:
    connection-string: ${AZURE_CONNECTION:}
    container-name: ${AZURE_CONTAINER_NAME:}

jwt:
  secret: ${JWT_SECRET:}
  tokens:
    ACCESS:
      expiration: 3600000
    REFRESH:
      expiration: 1209600000

security:
  token-encryption:
    key: ${TOKEN_ENCRYPTION_KEY:}
