apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mate
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
# 이미지 태그만 바꿀 때 예시:
# images:
#   - name: kusitmsmateacr.azurecr.io/mate
#     newTag: gha-5
