apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mate
resources:
- namespace.yaml
- secretstore-azurekv.yaml
- externalsecret-mate-env.yaml
- externalsecret-mate-mtls.yaml
- deployment.yaml
- poddisruptionbudget.yaml
- service.yaml
- ingress.yaml
- deployment-pdf.yaml
- service-pdf.yaml
images:
- name: kusitmsmateacr.azurecr.io/mate
  newTag: gha-72
- name: kusitmsmateacr.azurecr.io/mate-pdf
  newTag: gha-58
