{
 "title": "MATE 서버 로그",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Exception 발생 로그",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 23, "h": 6 },
   "targets": [
    {
     "expr": "{namespace=\"mate\"} |~ \"(?i)(exception|Exception)\" | json | line_format \"[{{.log_level}}] {{.message}}{{if .error_type}} type={{.error_type}}{{end}} logger={{.log_logger}}\""
    }
   ]
  },
  {
   "title": "K8s 시스템 에러",
   "type": "logs",
   "gridPos": { "x": 0, "y": 6, "w": 23, "h": 6 },
   "targets": [
    {
     "expr": "{namespace=\"kube-system\"} |~ \"(?i)(error|failed|fatal|panic)\" | json | line_format \"{{if .msg}}[{{.level}}] {{.msg}}{{if .error}} error={{.error}}{{end}}{{if .caller}} caller={{.caller}}{{end}}{{else}}{{__line__}}{{end}}\""
    }
   ]
  },
  {
   "title": "레벨별 로그 비율",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (log_level) (count_over_time({namespace=\"mate\"} | json | __error__=\"\" [1h]))"
    }
   ]
  },
  {
   "title": "Error 로그 수 ",
   "type": "logs",
   "gridPos": { "x": 0, "y": 20, "w": 23, "h": 4 },
   "targets": [
    {
     "expr": "sum by (namespace) (count_over_time({namespace=\"mate\"} | json | log_level=\"ERROR\" [1m]))"
    }
   ]
  },
  {
   "title": "로그 스트림",
   "type": "logs",
   "gridPos": { "x": 0, "y": 24, "w": 23, "h": 5 },
   "targets": [
    {
     "expr": "{namespace=\"mate\"} | json | __error__=\"\" | log_level=\"ERROR\" | line_format \"[{{.log_level}}] {{.message}} logger={{.log_logger}}\""
    }
   ]
  },
  {
   "title": "결제 로그",
   "type": "logs",
   "gridPos": { "x": 0, "y": 29, "w": 23, "h": 6 },
   "targets": [
    {
     "expr": "{namespace=\"mate\"} | json | log_logger=~ \"server.MATE.domain.payment.*\" | line_format \"[{{.log_level}}] {{.message}} logger={{.log_logger}}\""
    }
   ]
  },
  {
   "title": "Discord 봇 미발송 로그",
   "type": "logs",
   "gridPos": { "x": 0, "y": 35, "w": 23, "h": 6 },
   "targets": [
    {
     "expr": "{namespace=\"mate\"} | json | log_logger=~\"server.MATE.global.discord.(webhook.DiscordWebhookClient|outbox.service.DiscordOutboxService|outbox.scheduler.DiscordOutboxRetryScheduler)\" | log_level=~\"WARN|ERROR\" | line_format \"[{{.log_level}}] {{.message}} logger={{.log_logger}}\""
    }
   ]
  }
 ]
}