apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monitoring-alerts-from-kv
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-key-vault
    kind: SecretStore
  target:
    name: monitoring-alerts-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: discord-webhook-url
