apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-key-vault
  namespace: monitoring
spec:
  provider:
    azurekv:
      tenantId: b0a59db2-2285-4bcc-9cc0-5117fef10ebe
      vaultUrl: https://kusitms-mate-keyvault.vault.azure.net/
      authSecretRef:
        clientId:
          name: eso-azure-credentials
          key: ClientID
        clientSecret:
          name: eso-azure-credentials
          key: ClientSecret
